
import { GoogleGenAI, Modality } from "@google/genai";
import { MontageMode } from '../types';

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const processDataUrl = (dataUrl: string) => {
  const parts = dataUrl.split(',');
  if (parts.length !== 2) throw new Error('Invalid data URL');
  
  const mimePart = parts[0].match(/:(.*?);/);
  if (!mimePart || mimePart.length < 2) throw new Error('Invalid mime type in data URL');
  
  const mimeType = mimePart[1];
  const base64Data = parts[1];
  return { mimeType, base64Data };
};

const getPrompt = (mode: MontageMode, characterToReplace: string, optionalDetails: string) => {
    const details = optionalDetails ? `Specific instructions for posture/expression: ${optionalDetails}` : '';

    if (mode === 'insert') {
        return `You are an expert image editor. You will receive two images.
Image 1: A character, likely on a white or simple background.
Image 2: A scene.
Your task is to precisely replace the character described as '${characterToReplace}' in Image 2 with the character from Image 1.
- The inserted character must adopt the exact body posture and facial expression of the character being replaced.
- The lighting, shadows, and style of the inserted character must perfectly match the scene in Image 2.
- The rest of the scene from Image 2 must remain as faithful to the original as possible.
${details}`;
    } else { // recreate mode
        return `You are an expert digital artist. You will receive two images.
Image 1: A character, likely on a white or simple background.
Image 2: A scene that will serve as inspiration.
Your task is to generate a new scene that is heavily inspired by Image 2, but recreated from scratch to seamlessly incorporate the character from Image 1.
- In your newly generated scene, the character from Image 1 should replace the position and role of the character described as '${characterToReplace}' from the original scene (Image 2).
- The inserted character must replicate the body posture and facial expressions of the original character it is replacing.
- The overall mood, composition, and style of your new scene should match Image 2.
${details}`;
    }
};

export const createMontage = async (
    characterImage: string,
    sceneImage: string,
    characterToReplace: string,
    montageMode: MontageMode,
    optionalDetails: string
): Promise<string> => {
    try {
        const character = processDataUrl(characterImage);
        const scene = processDataUrl(sceneImage);

        const prompt = getPrompt(montageMode, characterToReplace, optionalDetails);
        
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [
                    { inlineData: { data: character.base64Data, mimeType: character.mimeType } },
                    { inlineData: { data: scene.base64Data, mimeType: scene.mimeType } },
                    { text: prompt },
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });
        
        const generatedPart = response.candidates?.[0]?.content?.parts?.[0];

        if (generatedPart && 'inlineData' in generatedPart && generatedPart.inlineData) {
            const { data, mimeType } = generatedPart.inlineData;
            return `data:${mimeType};base64,${data}`;
        }

        throw new Error("No image was generated by the API.");
    } catch (error) {
        console.error("Error creating montage:", error);
        if (error instanceof Error) {
           throw new Error(`Failed to generate montage: ${error.message}`);
        }
        throw new Error("An unknown error occurred while generating the montage.");
    }
};
